---
title: "STA5320_Final_Project"
author: "Patricia Rivera"
date: "5/8/2020"
margin: 2 cm
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(RColorBrewer)
library(gridExtra)
library(dplyr)
library(corrplot)
library(factoextra)
library(tidyverse)
library(broom)
library(modelr)
library(ISLR)

library(rsample) # data splitting
library(earth) # plotting
library(caret) # fit MARS model
library(vip) # variable importance
library(pdp) # variable relationships

library(glmnet)
library(caTools)
```

```{r}
attach(red_wine)
attach(white_wine)

# for convenience, make shorter variable names:
names(red_wine) <- c("fa","va","ca","rs","chl","fsd","tsd","den","ph","sul","alc","qual")
names(white_wine) <- names(red_wine)

head(white_wine)

red_wine$type <- "red"
white_wine$type <- "white"

wine <- rbind(red_wine,white_wine)
dim(wine)


```

```{r}
# --------- EXPLORATORY DATA ANALYSIS ------------

ggplot(wine, aes(x=fa, fill=type)) +geom_histogram(alpha=0.8,position = "dodge", bins = 15)+
  theme_minimal()+scale_fill_brewer(palette = "Set1")

ggplot(wine, aes(x=va, fill=type)) +geom_histogram(alpha=0.8,position = "dodge", bins = 15)+
  theme_minimal()+scale_fill_brewer(palette = "Set1")


ggplot(wine, aes(x=ca, fill=type)) +geom_histogram(alpha=0.8,position = "identity", bins = 15)+
  theme_minimal()+scale_fill_brewer(palette = "Set1")

prop.table(table(wine$qual))

# ------ variable 1: fixed acidity (fa) ---------
summary(red_wine$fa)

# red wine
ggplot(data = red_wine, aes(fa)) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=15)+ labs(title = "Histogram of fixed acidity in red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# white wine
ggplot(data = white_wine, aes(fa)) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=15)+ labs(title = "Histogram of fixed acidity in white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# -------- variable 2: volatile acidity (va) ---------
summary(red_wine$va)

# red wine
ggplot(data = red_wine, aes(va)) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=10)+ labs(title = "Histogram of volatile acidity in red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# white wine
ggplot(data = white_wine, aes(va)) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=10)+ labs(title = "Histogram of volatile acidity in white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# ------- Variable 3: citric acid (ca) ----------
summary(red_wine$ca)

# red wine
ggplot(data = red_wine, aes(ca)) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=30)+ labs(title = "Histogram of citric acid in red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))


# white wine
ggplot(data = white_wine, aes(ca)) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=30)+ labs(title = "Histogram of citric acid in white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))


# ------ variable 4: residual sugar (rs) --------
summary(red_wine$rs)

# red wine
ggplot(data = red_wine, aes(rs)) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=15)+ labs(title = "Histogram of residual sugar in red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# white wine
ggplot(data = white_wine, aes(rs)) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=15)+ labs(title = "Histogram of residual sugar in white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))


# ------ variable 5: chlorides (chl) -------
summary(red_wine$chl)

# red wine
ggplot(data = red_wine, aes(log(chl))) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=15)+ labs(title = "Histogram of chlorides in red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# white wine
ggplot(data = white_wine, aes(log(chl))) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=15)+ labs(title = "Histogram of chlorides in white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# ------- variable 6: free sulfur dioxide (fsd) --------
summary(red_wine$fsd)

# red wine
ggplot(data = red_wine, aes(fsd)) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=15)+ labs(title = "Histogram of free sulfur acid in red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# white wine
ggplot(data = white_wine, aes(fsd)) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=15)+ labs(title = "Histogram of free sulfur acid in white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))


# ------- variable 7: total sulfur dioxide (tsd) ---------
summary(red_wine$tsd)

# red wine
ggplot(data = red_wine, aes(tsd)) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=15)+ labs(title = "Histogram of total sulfur dioxide in red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# white wine
ggplot(data = white_wine, aes(tsd)) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=15)+ labs(title = "Histogram of total sulfur dioxide in white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))


# ------ variable 8: density(den) -------
summary(red_wine$den)

# red wine
ggplot(data = red_wine, aes(den)) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=15)+ labs(title = "Histogram of density of red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# red wine
ggplot(data = white_wine, aes(den)) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=15)+ labs(title = "Histogram of density of white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))


# --------- variable 9: pH ---------
summary(red_wine$ph)

# red wine
ggplot(data = red_wine, aes(ph)) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=15)+ labs(title = "Histogram of pH of red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# white wine
ggplot(data = white_wine, aes(ph)) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=15)+ labs(title = "Histogram of pH of white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))


# ----- variable 10: sulphates (sul) ---------
summary(red_wine$sul)

#red wine
ggplot(data = red_wine, aes(sul)) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=15)+ labs(title = "Histogram of sulphates in red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

#white wine
ggplot(data = white_wine, aes(sul)) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=15)+ labs(title = "Histogram of sulphates in white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# ------ variable 11: alcohol (alc) -------
summary(red_wine$alc)

# red wine
ggplot(data = red_wine, aes(alc)) + geom_histogram(col='black', fill = 'red', alpha=0.7, bins=15)+ labs(title = "Histogram of alcohol in red wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# white wine
ggplot(data = white_wine, aes(alc)) + geom_histogram(col='black', fill = 'blue', alpha=0.7, bins=15)+ labs(title = "Histogram of alcohol in white wine") + theme_minimal() + theme(plot.title = element_text(hjust=0.5))

# -------- variable 12: quality (qual) -------

# red wine
ggplot(data = red_wine, aes(qual)) + 
  geom_histogram(col='#290066', fill = '#c8d2ff', alpha=0.9, bins=6)+ 
  labs(title = "Distribution of quality ratings of red wine") + 
  theme_minimal() + 
  theme(plot.title = element_text(hjust=0.5))+
  xlab(label = "quality")

# white wine
ggplot(data = white_wine, aes(qual)) +
  geom_histogram(col='#290066', fill = '#c8d2ff', alpha=0.9, bins=8)+ 
  labs(title = "Distribution of quality ratings of white wine") + 
  theme_minimal() + 
  theme(plot.title = element_text(hjust=0.5))+ 
  xlab(label = "quality")

# faceted plot
h <- ggplot(wine, aes(x=qual))
h + stat_bin(breaks=seq(2,8,by=1), fill="#c8d2ff",
             col="#290066", alpha=1)+
  theme_minimal()+
  ylab(label = "Frequency")+
  facet_wrap(type~.) + 
  theme(strip.text.y = element_text(size = 10, face = "bold"), strip.background = element_rect(fill = "#c8d2ff"))+ 
  xlab(label = "Quality")

summary(red_wine)
```

```{r warning=F}
# faceted plot
h <- ggplot(wine, aes(x=alc))
h + stat_bin(breaks=seq(6,20,by=2), fill="#c8d2ff",
             col="#290066", alpha=1)+
  theme_minimal()+
  ylab(label = "Frequency")+
  facet_wrap(type~.) + 
  theme(strip.text.y = element_text(size = 10, face = "bold"), strip.background = element_rect(fill = "#c8d2ff"))+ 
  xlab(label = "Alcohol content")

```



```{r}
# CORRELATION PLOTS 
library(corrplot)

red_wine %>% 
  ggcorr(method = c("complete.obs", "pearson"),
                    nbreaks = 6, digits = 3, palette = "RdGy",
                    label = T, label_size = 4, label_color = "white",
                    label_round = 2)

white_wine %>% dplyr::select( -type) %>% 
  ggcorr(method = c("complete.obs", "pearson"),
                    nbreaks = 6, digits = 3, palette = "RdGy",
                    label = T, label_size = 4, label_color = "white",
                    label_round = 2)
```

# SECTION 2 : MLR, PCA, LASSO

# MULTIPLE LINEAR REGRESSION

```{r}
# RED WINE
mlr_1 <- lm(qual~., data = red_wine)
summary(mlr_1)

# variance inflation factor
car::vif(mlr_1)

mlr_2 <- lm(qual~. -fa, data = red_wine)
summary(mlr_2)

# checking model assumptions
par(mfrow=c(2,2), oma = c(1,1,0,0) + 0.1, mar = c(3,3,1,1) + 0.1)
plot(mlr_2)


# WHITE WINE

lin_white1 <- lm(qual~., data = white_wine)
summary(lin_white1)

lin_white2 <- lm(qual~. -den, data = white_wine)
summary(lin_white2)

lin_white3 <- lm(qual~. -den -ca, data = white_wine)
summary(lin_white3)

# checking model assumptions
par(mfrow=c(2,2), oma = c(1,1,0,0) + 0.1, mar = c(3,3,1,1) + 0.1)
plot(lin_white2)

anova(lin_white2, lin_white3)
car::vif(lin_white2)
```



# PRINCIPAL COMPONENT REGRESSION

```{r}
# --------- PCA --------------
# Red wine
red_wine %>% dplyr::select(-qual) %>% cbind() -> X_r

# defining standardizing function
stand <- function(x) (x-mean(x))/sd(x)

# standardized data matrix
X_rs <- apply(X_r,2,stand)

# find PC loadings matrix
pr_r <- prcomp(X_rs, scale. = T)

round(pr_r$rotation[,3],2)
# cutoff for "important" loadings
sqrt(1/ncol(X_r))


# scree plot
fviz_eig(prcomp(X_rs, scale. = T))

summary(prcomp(X_rs, scale. = T))

pc1 <- prcomp(X_r, scale. = T)$x[,1]
pc2 <- prcomp(X_r, scale. = T)$x[,2]
pc3 <- prcomp(X_r, scale. = T)$x[,3]
pc4 <- prcomp(X_r, scale. = T)$x[,4]
pc5 <- prcomp(X_r, scale. = T)$x[,5]
pc6 <- prcomp(X_r, scale. = T)$x[,6]
pc7 <- prcomp(X_r, scale. = T)$x[,7]
pc8 <- prcomp(X_r, scale. = T)$x[,8]
pc9 <- prcomp(X_r, scale. = T)$x[,9]
pc10 <- prcomp(X_r, scale. = T)$x[,10]
pc11 <- prcomp(X_r, scale. = T)$x[,11]

pca_lm <- lm(qual~pc1+pc2+pc3+pc4+pc5+pc6+pc7+pc8+pc9+pc10+pc11, data = red_wine)
pca_lm2 <- lm(qual~pc1+pc2+pc3+pc4+pc5+pc6, data = red_wine)


lmodpcr1 <- lm(red_wine$qual~pr_r$x[,1:11])
summary(lmodpcr1)
summary(pca_lm2)
summary(pca_lm)

list(pca_lm = broom::glance(pca_lm), pca_lm2 = broom::glance(pca_lm2))

# white wine

white_wine %>% dplyr::select(-qual) %>% cbind() -> X_w

# defining standardizing function
stand <- function(x) (x-mean(x))/sd(x)

# standardized data matrix
X_ws <- apply(X_w,2,stand)

# find PC loadings matrix
pr_w <- prcomp(X_ws, scale. = T)

# cutoff for "important" loadings
sqrt(1/ncol(X_w))

# scree plot
fviz_eig(prcomp(X_ws, scale. = T))

summary(prcomp(X_ws, scale. = T))
```



```{r}
# --------- MLR -------------



regfit.fwd <- regsubsets(qual~.,data = train_red, nvmax=12, method = "forward")
summary(regfit.fwd)
# testing performance of model
y_hat_red_best <- predict(model_train_red, test_red)
sqrt(mean(y_hat_red_best-test_red$qual)^2)

library(MASS)
# getting best model using step_wise selection with lowest AIC
best_red<- stepAIC(model_train_red, trace = F)
summary(best_red);summary(model_train_red)

list(model_train_red = broom::glance(model_train_red), best_red = broom::glance(best_red))


ridge <- train(qual~., data = train_red,
               method = "ridge",
               lambda = 4,
               preProcess = c("scale", "center"))
ridge

ridge.pred <- predict(ridge, test_red)
sqrt(mean(ridge.pred-test_red$qual)^2)


lmfit <- train(qual~., data = train_red,
               method = "lm", 
               trControl = fitControl,
               preProcess=c("scal", "center"))


```



# LOGISTIC REGRESSION

```{r}
# creating "type" variable for red and white wine data
red_wine$type <- "red"
white_wine$type <- "white"

wine <- rbind(red_wine,white_wine)

wine <- mutate(wine, qual2 =ifelse(qual<6, 0, 1))

# splitting training data into training and testing data in 70:30 ratio
train.split2 <- createDataPartition(wine$qual2, p=0.7)[[1]]

# training data with 70% total values
training_wine = wine[train.split2,]

# test data with 30% total values
test_wine = wine[-train.split2,]

# fitting logistic regression model
log_model_wine <- glm(qual2~. -qual -type, data = training_wine, family = "binomial")

# summary of model
summary(log_model_wine)

library(ROCR)
library(cvAUC)
pred_log_model <- predict(log_model_wine, test_wine, type = "response")
pr <- prediction(pred_log_model, test_wine$qual2)
prf0 <- performance(pr, measure = "tpr", x.measure = "fpr")
out <- cvAUC(pred_log_model, test_wine$qual2)
out$cvAUC


AUC(pred_log_model, test_wine$qual2)

# second logistic regression model
log_mod2 <- glm(qual2~ va +rs+fsd*tsd+sul+alc+ph+den*alc, data = training_wine, family = "binomial")
pred_log2 <- predict(log_mod2, test_wine, type = "response")
pr1 <- prediction(pred_log2, test_wine$qual2)
prf1 <- performance(pr1, measure = "tpr", x.measure = "fpr")
out1 <- cvAUC(pred_log2, test_wine$qual2)
out1$cvAUC

log_mod3 <- glm(qual2~. -type -qual -chl -den , data = training_wine, family = "binomial")
pred_log3 <- predict(log_mod3, test_wine, type = "response")

AUC(pred_log3, test_wine$qual2)
AUC(pred_log2, test_wine$qual2)




library(e1071)
confusionMatrix(
  factor(test_wine$qual2, levels = 0:1),
  factor(predictedy_hat_wine, levels = 0:1)
)




```

# RANDOM FOREST

```{r}
library(randomForest)
forest <- randomForest:: randomForest(as.factor(qual2)~. -type -qual, data=training_wine, ntree = 250, mtry=3, importance = TRUE)

pred_forest <- predict(forest, test_wine, "prob")
#output <- pred_forest[,2]
#pr2 <- prediction(output, test_wine$qual2)
#prf2 <- performance(pr2, measure = "tpr", x.measure = "fpr")

#auc2 <- performance(pr2, measure = "auc")
#auc2 <- auc2@y.values[[1]]
#auc2

AUC(as.numeric(pred_forest), test_wine$qual2)
```

# XGBOOST

```{r}
library(gbm)
set.seed(1)
boost <- gbm(qual2~. -type -qual, data = training_wine,
             distribution = "bernoulli",
             n.trees = 5000, shrinkage = 0.2,
             interaction.depth = 4)
boost_pred <- predict(boost, test_wine[-12:-13], n.trees = 5000)


#pr4 <- prediction(boost_pred, test_wine$qual2)
#prf4 <- performance(pr, measure = "tpr", x.measure = "fpr")

#auc4 <- performance(pr4, measure = "auc")
#auc4 <- auc4@y.values[[1]]
#auc4

AUC(boost_pred, test_wine$qual2)


## PLOTTING ROC CURVES
#plot(prf1, main="ROC Curves") # Logistic Regression (BLACK)
#plot(prf2, add = T, col=2) # RF (RED)
#plot(prf4, add = T, col = 3) # Boosting (GREEN)
#abline(0,1)
#legend(0.66, 0.4, legend = c("Logistic Regression", "Random Forest", "Boosting"), col #= c("Black", "Red", "Green"), lty = 1, cex=0.8, title= "Models")





rf_mod <- randomForest::randomForest(as.factor(qual2)~. -type - qual, data = training_wine, ntree=250, importance = T)

rf_pred <- predict(rf_mod, test_wine)

AUC(as.numeric(rf_pred), test_wine$qual2)

mean((as.numeric(rf_pred)-test_wine$qual2)^2)
mean((boost_pred-test_wine$qual2)^2)
```




```{r}
library(leaps)
fit1 <- lm(qual~., data = red_wine)
summary(fit1)

fit2 <- lm(qual~va+chl+fsd+tsd+ph+sul+alc, data=red_wine)
summary(fit1);summary(fit2)

list(fit1 = broom::glance(fit1), fit2 = broom::glance(fit2))

test_set %>% gather_predictions(fit1, fit2) %>% group_by(model) %>% summarise(MSE=mean(qual-pred)^2)


```

# SECTION 2 CONTINUED

```{r}
red_wine <- red_wine[,-13]
mars1 <- earth(qual~., data = red_wine)
print(mars1)

summary(mars1) %>% .$coefficients %>% head(10)


# create a tuning grid
hyper_grid <- expand.grid(
  degree = 1:3, 
  nprune = seq(2, 100, length.out = 10) %>% floor()
  )

# for reproducibiity
set.seed(123)

# cross validated model
tuned_mars <- caret::train(
  x = subset(red_wine, select = -qual),
  y = red_wine$qual,
  method = "earth",
  metric = "RMSE",
  trControl = trainControl(method = "cv", number = 10),
  tuneGrid = hyper_grid
)

# best model
tuned_mars$bestTune
##    nprune degree
## 3     23      1

# plot results
ggplot(tuned_mars)
```

```{r}
set.seed(123)
cv_mod1 <- caret::train(qual~.,
                        data=red_wine,
                        method="lm",
                        metric="RMSE",
                        trControl = trainControl(method = "cv", number = 10))
```


```{r}
set.seed(123)
split = sample.split(red_wine$qual, SplitRatio = 0.80)
training_set = subset(red_wine, split == TRUE)
test_set = subset(red_wine, split == FALSE)

red_train <- model.matrix(qual~., training_set)[,-1]
red_train_y <- log(training_set$qual)

red_test <- model.matrix(qual~., test_set)[,-1]
dim(red_train)

# Apply Ridge regression to red wine data
red_ridge <- cv.glmnet(
  x = red_train,
  y = red_train_y,
  alpha = 0
)
plot(red_ridge)
plot(red_ridge, xvar = "lambda")

min(red_ridge$cvm) # minimum MSE
red_ridge$lambda.min

coef(red_ridge, s = "lambda.1se") %>%
  tidy() %>%
  filter(row != "(Intercept)") %>%
  top_n(25, wt = abs(value)) %>%
  ggplot(aes(value, reorder(row, value))) +
  geom_point() +
  ggtitle("Top 25 influential variables") +
  xlab("Coefficient") +
  ylab(NULL)
```


# LASSO
```{r}
# Apply Ridge regression to red wine data
red_lasso <- glmnet(
  x = red_train,
  y = training_set$qual,
  alpha = 1
)

plot(red_lasso, xvar="lambda")

x=model.matrix(qual~.,red_wine)[,-1]
y=red_wine$qual

grid = 10^seq(10,-2,length=100)
ridge.mod = glmnet(x,y, lambda = grid)
coef(ridge.mod)[,10]
```

```{r}
library(pls)
set.seed(2)
pcr.fit = pcr(qual~., data=red_wine, scale=TRUE, validation="CV")
summary(pcr.fit)
validationplot(pcr.fit, val.type = "MSEP")

set.seed(1)
pcr.fit2 = pcr(qual~., data=red_wine, subset=red_train, scale=TRUE, validation="CV")
validationplot(pcr.fit2, val.type = "MSEP")

pcr.pred = predict(pcr.fit2,x[red_test,], ncomp = 9)
mean((pcr.pred- test_set$qual )^2)
```

